name: "base"
launch:
  - include:
      file: "$(find-pkg-share romea_mobile_base_meta_bringup)/profile/robot.launch.py"
      arg:
        - name: "joystick_topic"
          value: "/adap2e/joystick/joy"
        - name: "joystick_configuration_file_path"
          value: "$(find-pkg-share romea_joystick_utils)/config/microsoft_xbox.yaml"
  - include:
      file: "$(find-pkg-share romea_mobile_base_meta_bringup)/profile/localisation_plugin.launch.py"
configuration:
  manufacturer: inrae
  model: adap2e
  version: fat
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  initial_xyz: [1.0, 0.0, 0.0]
  initial_rpy: [0.0, 0.0, 0.0]
