remote_controller:
  type: joystick
  available_mode: all
lms151:
  type: lidar
  available_mode: none
septentrio:
  type: gps
  available_mode: none
xsens:
  type: imu
  available_mode: none
ur10:
  type: arm
  available_mode: simulation
axis:
  type: camera
  available_mode: none
zed1:
  type: stereo_camera
  available_mode: none
realsense:
  type: camera
  available_mode: none
