name: "lidar"
launch:
  - include:
      file: "$(find-pkg-share romea_lidar_meta_bringup)/profile/sick_scan_xd_lms1xx.launch.py"
      arg:
        - name: ip
          value: "192.168.1.112"
        - name: port
          value: "2112"
configuration:
  manufacturer: sick
  model: lms
  version: 151
  rate: 50
  resolution: 0.5
location:
  parent_link: "base_link"
  xyz: [2.02, 0.0, 0.34]
  rpy: [0.0, 0.0, 0.0]
records:
  scan: true
  cloud: false
