name: gps
launch:
  - include:
      file: "$(find-pkg-share romea_gps_meta_bringup)/profile/romea_gps_serial_driver.launch.py"
      arg:
        - name: device
          value: /dev/ttyUSB0
        - name: baudrate
          value: "115200"
  - include:
      file: "$(find-pkg-share romea_gps_meta_bringup)/profile/localisation_plugin.launch.py"
      arg:
        - name: wgs84_anchor_file_path
          value: $(var wgs84_anchor_file_path)
        - name: odom_topic
          value: /$(var robot_namespace)/base/controller/odom
  - include:
      file: "$(find-pkg-share romea_gps_meta_bringup)/profile/ntrip_client.launch.py"
      arg:
        - name: mountpoint
          value: MTLDR
configuration:
  manufacturer: septentrio
  model: asterx
  rate: 10
  dual_antenna: true
location:
  parent_link: "base_link"
  xyz: [0.0, 0.3, 1.5]
records:
  nmea_sentence: true
  gps_fix: false
  vel: false
