name: arm
launch:
  - node:
      pkg: romea_common_meta_bringup
      exec: urdf_broadcaster_node
      name: ros2_control_description
      param:
        - name: robot_description
          value: $(var ros2_control_description)
  - include:
      file: "$(find-pkg-share romea_arm_meta_bringup)/profile/ur.launch.py"
      arg:
        - name: ip
          value: "1.1.1.1"
configuration:
  manufacturer: universal_robots
  model: ur
  version: "10"
location:
  parent_link: "base_link"
  xyz: [2.02, 0.0, 0.54]
  rpy: [0.0, 0.0, 0.0]
simulation:
  initial_joint_positions:
    shoulder_pan_joint: 0.0
    shoulder_lift_joint: -80.0
    elbow_joint: 155.0
    wrist_1_joint: 90.0
    wrist_2_joint: -90.0
    wrist_3_joint: 0.0
records:
  joint_states: false
